# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       harbour-vipiano

# >> macros
%define __provides_exclude_from ^%{_datadir}/.*$
# libsndfile shouldn't be excluded but for some reason it causes Harbour validator to fail
%define __requires_exclude ^libfluidsynth|libsndfile.*$
# << macros

Summary:    A piano synthesizer
Version:    0.1
Release:    1
Group:      Qt/Qt
License:    GPLv3+ and LGPLv2+ and MIT
URL:        https://github.com/Aldrog/harbour-vipiano
Source0:    %{name}-%{version}.tar.bz2
Source100:  harbour-vipiano.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(gthread-2.0)
BuildRequires:  pkgconfig(libpulse-simple)
BuildRequires:  pkgconfig(sndfile)
BuildRequires:  pkgconfig(audioresource)
BuildRequires:  pkgconfig(vorbis)
BuildRequires:  cmake
BuildRequires:  desktop-file-utils

%description
Short description of my Sailfish OS Application


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
mkdir -p rpmbuilddir
cd rpmbuilddir &&  cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ..
cd ..
make -C rpmbuilddir %{?_smp_mflags}
# << build pre



# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
DESTDIR=%{buildroot} make -C rpmbuilddir install
mkdir -p %{_bindir}
# << install pre

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/*/apps/%{name}.png
# >> files
# << files
